#!/usr/bin/with-contenv bash

ENABLE_ZABBIX=${ENABLE_ZABBIX:-"TRUE"}
ZABBIX_LOGFILE=${ZABBIX_LOGFILE:-"/var/log/zabbix/zabbix_agent2.log"}
ZABBIX_LOGFILESIZE=${ZABBIX_LOGFILESIZE:-"1"}
ZABBIX_DEBUGLEVEL=${ZABBIX_DEBUGLEVEL:-"1"}
ZABBIX_SERVER=${ZABBIX_SERVER:-"0.0.0.0/0"}
ZABBIX_LISTEN_PORT=${ZABBIX_LISTEN_PORT:-"10050"}
ZABBIX_SERVER_ACTIVE=${ZABBIX_SERVER_ACTIVE:-"zabbix-proxy"}
ZABBIX_HOSTNAME=${ZABBIX_HOSTNAME:-"docker"}
ZABBIX_REFRESH_ACTIVE_CHECKS=${ZABBIX_REFRESH_ACTIVE_CHECKS:-"120"}
ZABBIX_BUFFER_SEND=${ZABBIX_BUFFER_SEND:-"5"}
ZABBIX_BUFFER_SIZE=${ZABBIX_BUFFER_SIZE:-"100"}
ZABBIX_PERSISTENT_BUFFER=${ZABBIX_PERSISTENT_BUFFER:-"0"}
ZABBIX_PERSISTENT_BUFFER_PERIOD=${ZABBIX_PERSISTENT_BUFFER_PERIOD:-"1h"}
ZABBIX_PROCESS_TIMEOUT=${ZABBIX_PROCESS_TIMEOUT:-"5"}
ZABBIX_MAXLINES_SECOND=${ZABBIX_MAXLINES_SECOND:-"20"}
ZABBIX_REMOTECOMMANDS_ALLOW=${ZABBIX_REMOTECOMMANDS_ALLOW:-"*"}
ZABBIX_REMOTECOMMANDS_LOG=${ZABBIX_REMOTECOMMANDS_LOG:-"1"}

if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
  ZABBIX_DEBUGLEVEL=4
fi

if [ "$ENABLE_ZABBIX" = "TRUE" ] || [ "$ENABLE_ZABBIX" = "true" ]; then
  echo "[i] Enable Zabbix Agent2"
  sed -i -e "s|<ZABBIX_LOGFILE>|$ZABBIX_LOGFILE|g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_LOGFILESIZE>/$ZABBIX_LOGFILESIZE/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_DEBUGLEVEL>/$ZABBIX_DEBUGLEVEL/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s|<ZABBIX_SERVER>|$ZABBIX_SERVER|g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_LISTEN_PORT>/$ZABBIX_LISTEN_PORT/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_SERVER_ACTIVE>/$ZABBIX_SERVER_ACTIVE/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_HOSTNAME>/$ZABBIX_HOSTNAME/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_REFRESH_ACTIVE_CHECKS>/$ZABBIX_REFRESH_ACTIVE_CHECKS/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_BUFFER_SEND>/$ZABBIX_BUFFER_SEND/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_BUFFER_SIZE>/$ZABBIX_BUFFER_SIZE/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_PERSISTENT_BUFFER>/$ZABBIX_PERSISTENT_BUFFER/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_PERSISTENT_BUFFER_PERIOD>/$ZABBIX_PERSISTENT_BUFFER_PERIOD/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_PROCESS_TIMEOUT>/$ZABBIX_PROCESS_TIMEOUT/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_MAXLINES_SECOND>/$ZABBIX_MAXLINES_SECOND/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_REMOTECOMMANDS_ALLOW>/$ZABBIX_REMOTECOMMANDS_ALLOW/g" /etc/zabbix/zabbix_agent2.conf
  sed -i -e "s/<ZABBIX_REMOTECOMMANDS_LOG>/$ZABBIX_REMOTECOMMANDS_LOG/g" /etc/zabbix/zabbix_agent2.conf
  
  if [ -n "${ZABBIX_REMOTECOMMANDS_DENY}" ]; then
    echo "DenyKey=system.run[${ZABBIX_REMOTECOMMANDS_DENY}]" >> /etc/zabbix/zabbix_agent2.conf
  fi

  mkdir -p ${ZABBIX_LOGFILE%/*}
  chown -R $ZABBIX_USER ${ZABBIX_LOGFILE%/*}
  chown -R $ZABBIX_USER /etc/zabbix/
else
  echo "[i] Disable Zabbix Agent2"
  s6-svc -d /var/run/s6/services/`basename $0`
fi

mkdir -p /tmp/state
touch /tmp/state/`basename $0`-init
