#!/usr/bin/with-contenv bash

## Timezone Setup
if [ -n "$TIMEZONE" ]; then 
  set_timezone () {
    if [ -f /usr/share/zoneinfo/$TIMEZONE ];  then
       echo "[i] Setting timezone to $TIMEZONE"
       cp -R /usr/share/zoneinfo/$1 /etc/localtime
       echo $1 > /etc/timezone
    else
       echo "[i] ERROR: Timezone $TIMEZONE does not exist - Skipping.."
    fi
  } 

mkdir -p /tmp/state
touch /tmp/state/99-container-init
