#!/usr/bin/with-contenv bash
while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

CRON_CMD=${CRON_CMD:-""}

if [ ! -f /tmp/state/`basename $0` ]; then
  sleep 30
  sed -e "s|<CRON_CMD>|$CRON_CMD|g" -i /sfiles/cron/crontab.txt
  mkdir -p /tmp/state/
  echo 'Initialization Complete' >/tmp/state/`basename $0`
fi

if [ -d /sfiles/cron/cron-custom ]; then
  echo '[i] Found Custom Crontab - Merging'
  cat /assets/cron/cron-custom/* >>/assets/cron/crontab.txt
fi

echo '[i] Starting cron'
/usr/bin/crontab /sfiles/cron/crontab.txt
exec /usr/sbin/crond -f -l 8 >/dev/null 2>&1;
